include themes/tokyonight-storm.conf

font_family family="Maple Mono NFMono CN" features="-calt +cv01 +cv02 +cv04"
font_size 15

initial_window_width 120c
initial_window_height 36c

window_padding_width 36

tab_bar_edge top
tab_bar_min_tabs 1
tab_bar_style slant
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index} {title}"
